# Copyright 2022 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

name: CI Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.1.15"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        shell: bash
        run: |
          pip install poetry==${{ matrix.poetry-version }}m
      - name: Install Dependencies
        run: python -m poetry install
      - name: Configure Validation
        run: python -m poetry run make validate-setup
      - name: Validate Sources
        run: python -m poetry run make validate
      - name: Start Container
        run: python -m poetry run bin/docker-utils.sh -u
      - name: Wait for Container Start
        run: sleep 30
      - name: Run Tests
        run: python -m poetry run make test
      - name: Stop Container
        run: python -m poetry run bin/docker-utils.sh -d
